### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by nerahmou** [ARASHz4/signalr_socket_flutter#1]
When I launch the example with my config I get this:

`I/flutter (13310): signalr socket update connection status connecting`
`I/flutter (13310): signalr socket update connection status connectingError`
`I/flutter (13310): signalr socket update connection status disconnected`
`I/flutter (13310): signalr socket update connection status connectingError`

**Comment by ARASHz4** [comment]
What is your platform?
Did you enter your server address and hub name and event name?
If in your server use signalR .netCore this library not support .netCore

**Comment by nerahmou** [comment]
- Android.
- My server doesn't use Core.

This is my code:
```
SignalrSocket(
      url: "https://hub.xxxxx.com",
      hubName: "TestHub",
      eventName: "sendOrder",
      queryString: {'id': 'xxxxxxxxxxxxxxxxxxxxxxxxxx'},
      updateConnectionStatus: (connectionStatus) {
        debugPrint("signalr socket update connection status ${connectionStatus.name}");
      },
      newMessage: newMessage,
    );
```

**Comment by ARASHz4** [comment]
I tested and work fine, should be a problem from server side
